POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "primeiro vídeo",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=

###

PUT http://localhost:3333/videos/
Content-Type: application/json

{
    "title": "Video teste",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/84d99739-dd0a-405a-a1f4-18b16dc8b1eb

